// <auto-generated />
namespace SuperZapatos.InvetoryControl.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Standard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Standard));
        
        string IMigrationMetadata.Id
        {
            get { return "201702100102145_Standard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
